<a href="https://colab.research.google.com/github/SIDED00R/SIDED00R/blob/main/5%EC%A3%BC%EC%B0%A8_%EC%8B%A4%EC%A0%84%EA%B8%B0%EA%B3%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt


In [14]:
x=torch.ones(3,2)
print(x)
x=torch.zeros(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [16]:
torch.manual_seed(2)
x=torch.rand(3,2)
print(x)
x=torch.randn(3,3)
print(x)


tensor([[0.6147, 0.3810],
        [0.6371, 0.4745],
        [0.7136, 0.6190]])
tensor([[-2.1409, -0.5534, -0.5000],
        [-0.0815, -0.1633,  1.5277],
        [-0.4023,  0.0972, -0.5682]])


In [17]:
x=torch.tensor([[1,2],
               [3,4],
               [5,6]])
print(x[:,1])
print(x[0,:])
y=x[1,1]
print(y)

tensor([2, 4, 6])
tensor([1, 2])
tensor(4)


In [22]:
x=torch.tensor([[1,2],
               [3,4],
               [5,6]])
y=x.view(2,3)
print(y)
y=x.view(6,-1) #-1은 자동으로 숫자 채워줌
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [27]:
x=torch.ones([3,2])
y=torch.ones([3,2])
z=x+y
print(z)
z=torch.add(x,y)
print(z)
z=x-y
print(z)
z=torch.sub(x,y)
print(z)

#y=y+x -> y+=x
y.add_(x) #y+=x
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [29]:
x=torch.linspace(0,1,steps=5)
print(x)
x_np=x.numpy()
print(type(x),type(x_np))

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [30]:
a=np.random.randn(5)
a_pt=torch.from_numpy(a)
print(a)
print(type(a),type(a_pt))

[ 0.58465306 -1.11838723 -0.837937    1.05599008 -1.36238818]
<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [3]:
print(torch.cuda.device_count())

1


In [5]:
cuda0=torch.device('cuda:0')
a=torch.ones(3,2,device=cuda0)
b=torch.ones(3,2,device=cuda0)
c=a+b
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')


In [6]:
c=c.cpu()
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [7]:
x=torch.ones([3,2],requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [12]:
y=x+5
print(y)

z=y*y+1
print(z)
t=torch.sum(z)
print(t)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)
tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)
tensor(222., grad_fn=<SumBackward0>)


In [13]:
t.backward()
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [15]:
print(torch.cuda.get_device_name(0))

Tesla K80
